Project/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class ShoppingCartController : Controller
    {
        ProjectEntities db = new ProjectEntities();
        // GET: ShoppingCart
        [HttpGet]
         public ActionResult Index()
        {
            if (Session["cartid"] != null)
            {
              string str  =Session["cartid"].ToString();
                var q = from m in db.Carts.ToList()
                        where m.Cartid == str
                        select m;
                return View(q);
            }
            return RedirectToAction("Index","Home");
        }
        [HttpPost]
        public ActionResult Index(int albumid,int qty)
        {
            Cart obj = new Cart();
            obj.Cartid = GetCartId();
            obj.Albumid = albumid;
            obj.DateCreated = DateTime.Now;
            obj.Quantity = qty;
            db.Carts.Add(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [NonAction]
        public string GetCartId()
        {
            if (Session["cardid"] == null)
            {
                Session["cartid"] = Guid.NewGuid().ToString();
            }
            return Session["cartid"].ToString();
        }
        public ActionResult Second()
        {
            return View();
        }
        public ActionResult Confirm()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Confirm( Customer obj)
        {
            
            obj.OraderDate = DateTime.Now;
                obj.Total = (int)Session["total"];
            db.Customers.Add(obj);
            db.SaveChanges();
            TempData["custmerid"] = obj.CustomerId;
            //2.move items from cart to orderdetails
            string str = Session["cartid"].ToString();
            var q = from m in db.Carts.ToList()
                    where m.Cartid == str
                    select m;
            foreach (var item in q)
            {
                OrderDetail ord = new OrderDetail();
                ord.CustomerId = obj.CustomerId;
                ord.Albumid = item.Albumid;
                ord.Quantity = item.Quantity;
                ord.UnitPrice = item.Album.UnitPrice;
                db.OrderDetails.Add(ord);
                db.SaveChanges();
            }
            //3.step is delete item from cart 
            foreach (var item in q)
            {
                db.Carts.Remove(item);
                db.SaveChanges();
            }

            return RedirectToAction("Complete");
        }
        public ActionResult Delete(int id)
        {
           Cart obj= db.Carts.Find(id);
            db.Carts.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
     public ActionResult Complete()
        {

            return View(db.OrderDetails.ToList());
        }

    }
}

Project/Controllers/StoreMangerController.cs
using Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    [Authorize]
    public class StoreMangerController : Controller
    {
        ProjectEntities db = new ProjectEntities();
        public ActionResult Index()
        {
            List<Album> alubum = db.Albums.ToList();
            return View(alubum);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View();
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Album album = db.Albums.Find(id);
            return View(album);
        }
        [HttpPost]
        public ActionResult Edit(Album album)
        {
            if (TryUpdateModel(album))
            {
                if (ModelState.IsValid)
                {
                    db.Entry(album).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            Album album = db.Albums.Find(id);
            return View(album);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Album album = db.Albums.Find(id);
            return View(album);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmation(Album album,int id)
        {
            album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
      
    }
}

Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/DataTables/css/dataTables.jqueryui.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#ccffe6; height:80px;">
        <div class="container">
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home |", "Index", "Home", new { area = "" }, new { @class = "navbar-brand"})
                @Html.ActionLink("Store |", "ShowAll", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Cart |", "Index", "ShoppingCart", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Admin |", "Index", "StoreManger", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                </ul>
            </div>
        </div>
    </div>
   
    <br /><br />
    <br /><br />
    <div class="container body-content">
        @RenderBody()
        <br />
        <br />
        <hr />
        <br />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    <script src="~/scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    
    <script src="~/scripts/DataTables/jquery.dataTables.js"></script>
</body>
</html>

Project/Views/Shared/_Second.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    
    @RenderBody()
    <script src="~/scripts/jquery-3.1.1.js"></script>
    <script src="~/scripts/bootstrap.js"></script>
</body>
</html>